openapi: 3.0.0
info:
  title: Cart API
  version: 1.0.0
paths:
  /carts/:
    get:
      summary: Retrieve all carts
      operationId: getCarts
      responses:
        '200':
          description: List of carts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'
    post:
      summary: Create a new cart
      operationId: createCart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartCreateRequest'
      responses:
        '201':
          description: Cart created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
  /carts/{cartId}/:
    get:
      summary: Retrieve a single cart
      operationId: getCart
      parameters:
        - name: cartId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
    post:
      summary: Update a cart with new items
      operationId: updateCart
      parameters:
        - name: cartId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartUpdateRequest'
      responses:
        '200':
          description: Cart updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
    delete:
      summary: Delete a cart
      operationId: deleteCart
      parameters:
        - name: cartId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Cart deleted
  /carts/{cartId}/delete-item/:
    post:
      summary: Delete a specific quantity of an item in a cart
      operationId: deleteCartItem
      parameters:
        - name: cartId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteItemRequest'
      responses:
        '200':
          description: Cart updated with item deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
components:
  schemas:
    Cart:
      type: object
      properties:
        id:
          type: string
        hash:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
    CartItem:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        quantity:
          type: integer
        price:
          type: number
          format: float
    CartCreateRequest:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
    CartUpdateRequest:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
    DeleteItemRequest:
      type: object
      properties:
        item_id:
          type: string
        quantity:
          type: integer
          example: 1
