# Generated by Django 4.2.1 on 2023-05-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_cartitem_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
